# Generated by Django 2.2.7 on 2019-11-18 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPaymentsTransaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('legacy_address', models.CharField(max_length=150, verbose_name='Legacy Address')),
                ('destination_tag', models.CharField(max_length=150, verbose_name='Destination Tag')),
                ('coin_amount', models.FloatField(default=0, verbose_name='Coin Amount')),
                ('coin_received_amount', models.FloatField(default=0, verbose_name='Coin Received Amount')),
                ('status_url', models.URLField(verbose_name='Status Url')),
                ('qr_code', models.URLField(verbose_name='QR Code')),
            ],
            options={
                'verbose_name': 'CoinPayments Transaction',
                'verbose_name_plural': 'CoinPayments Transactions',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('coin_amount', models.FloatField(blank=True, null=True, verbose_name='Coin Amount')),
                ('network_fee', models.FloatField(blank=True, null=True, verbose_name='Network Fee')),
                ('commission', models.FloatField(blank=True, null=True, verbose_name='Commission')),
                ('tx_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='tx_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150, verbose_name='Coin Address')),
                ('legacy_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Legacy Address')),
                ('destination_tag', models.CharField(blank=True, max_length=150, null=True, verbose_name='Destination Tag')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('coin_amount', models.FloatField(blank=True, null=True, verbose_name='Coin Amount')),
                ('currency_type', models.CharField(choices=[('bitcoincash', 'Bitcoin Cash'), ('litecoin', 'Litecoin'), ('bitcoin', 'Bitcoin'), ('dash', 'Dash'), ('bitcoincash', 'Bitcoin Cash'), ('xrp', 'XRP'), ('ethereum', 'Ethereum'), ('litecointestnet', 'Litecoin Testnet')], default='bitcoin', max_length=8, verbose_name='Currency Type')),
                ('recipient_name', models.CharField(blank=True, max_length=250, null=True, verbose_name="Customer's name")),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Customer's email")),
                ('reference', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('COMPL', 'Completed'), ('PEND', 'Pending'), ('NEW', 'new')], max_length=4)),
                ('approved', models.BooleanField(default=False, editable=False, verbose_name='Approved')),
                ('provider_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alfacoins_model.WithdrawalTransaction', verbose_name='Withdrawal transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_type', models.CharField(choices=[('bitcoincash', 'Bitcoin Cash'), ('litecoin', 'Litecoin'), ('bitcoin', 'Bitcoin'), ('dash', 'Dash'), ('bitcoincash', 'Bitcoin Cash'), ('xrp', 'XRP'), ('ethereum', 'Ethereum'), ('litecointestnet', 'Litecoin Testnet')], default='bitcoin', max_length=8, verbose_name='Currency Type')),
                ('currency', models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'European Pounds')], default='USD', max_length=8, verbose_name='Payment currency')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('amount_paid', models.FloatField(verbose_name='Amount paid')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('COMPL', 'Completed'), ('PPD', 'Partially paid'), ('REF', 'Refunded'), ('EXPR', 'Expired'), ('PAID', 'Paid')], max_length=4)),
                ('payerName', models.CharField(blank=True, max_length=250, null=True, verbose_name="Customer's name")),
                ('payerEmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Customer's email")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('timeout', models.DateTimeField(editable=False, verbose_name='Valid until')),
                ('provider_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alfacoins_model.CoinPaymentsTransaction', verbose_name='Payment transaction')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
