# Generated by Django 2.2.7 on 2019-11-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfacoins_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinpaymentstransaction',
            name='confirms_needed',
        ),
    ]
