# Generated by Django 2.2.7 on 2019-11-17 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alfacoins_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('coin_amount', models.FloatField(verbose_name='Coin Amount')),
                ('tx_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='tx_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('legacy_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Legacy Address')),
                ('destination_tag', models.CharField(blank=True, max_length=150, null=True, verbose_name='Destination Tag')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('coin_amount', models.FloatField(blank=True, null=True, verbose_name='Coin Amount')),
                ('currency_type', models.CharField(choices=[('bitcoincash', 'Bitcoin Cash'), ('litecoin', 'Litecoin'), ('bitcoin', 'Bitcoin'), ('dash', 'Dash'), ('bitcoincash', 'Bitcoin Cash'), ('xrp', 'XRP'), ('ethereum', 'Ethereum'), ('litecointestnet', 'Litecoin Testnet')], default='bitcoin', max_length=8, verbose_name='Currency Type')),
                ('recipient_name', models.CharField(blank=True, max_length=250, null=True, verbose_name="Customer's name")),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Customer's email")),
                ('reference', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('COMPL', 'Completed'), ('PEND', 'Paid')], max_length=4)),
                ('approved', models.BooleanField(default=False, editable=False, verbose_name='Approved')),
                ('provider_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alfacoins_model.WithdrawalTransaction', verbose_name='Withdrawal transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
