# Generated by Django 2.2.7 on 2019-11-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfacoins_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='type',
            new_name='currency_type',
        ),
    ]
