# Generated by Django 2.2.7 on 2019-11-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfacoins_model', '0002_withdrawal_withdrawaltransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinpaymentstransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='coinpaymentstransaction',
            name='iframe_url',
        ),
        migrations.AddField(
            model_name='coinpaymentstransaction',
            name='coin_amount',
            field=models.FloatField(default=0, verbose_name='Coin Amount'),
        ),
        migrations.AddField(
            model_name='coinpaymentstransaction',
            name='coin_received_amount',
            field=models.FloatField(default=0, verbose_name='Coin Received Amount'),
        ),
    ]
