# Generated by Django 2.2.7 on 2019-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfacoins_model', '0002_auto_20191118_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('COMPL', 'Completed'), ('PEND', 'Pending')], max_length=4),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='commission',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='network_fee',
            field=models.FloatField(blank=True, null=True, verbose_name='Network Fee'),
        ),
    ]
