# Generated by Django 2.2.7 on 2019-11-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfacoins_model', '0003_auto_20191118_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='coin_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Coin Amount'),
        ),
    ]
